import os
import google.generativeai as genai

genai.configure(api_key=os.environ["GEMINI_API_KEY"])

# Create the model
generation_config = {
  "temperature": 1,
  "top_p": 0.95,
  "top_k": 40,
  "max_output_tokens": 8192,
  "response_mime_type": "text/plain",
}

model = genai.GenerativeModel(
  model_name="gemini-1.5-flash",
  generation_config=generation_config,
)

# Pre-trained outputs
predefined_outputs = [
  "input: zucchini, cherry tomatoes, garlic, and olive oil\nvegan",
  "output: ## Your Ingredients\n1. Zucchini\n2. Cherry tomatoes\n3. GarlicOlive oil\n\nHere are my 3 recommended recipes:\n\n## Recipe 1: Roasted Zucchini & Cherry Tomatoes\n1. **Prep:** Preheat oven to 400°F (200°C). Line a baking sheet with parchment.\n2. **Arrange:** Slice zucchini (1/4-inch rounds), halve tomatoes. Spread on the sheet.\n3. **Season:** Mince garlic, sprinkle on veggies, drizzle with olive oil, add salt and pepper.\n4. **Roast:** Toss to coat, then roast for 20-25 mins until veggies are tender.\n(Extra Tips: Flip halfway for even browning; great as a side, pasta mix-in, or grain topping)\n\n## Recipe 2: Sautéed Zucchini & Tomatoes\n1. Prep: Slice zucchini (half-moons), halve tomatoes.\n2. Cook: Heat olive oil in a skillet over medium. Sauté garlic until fragrant, then add zucchini for 5-7 mins.\n3. Finish: Add tomatoes, cook 3-5 mins. Season with salt and pepper.\n(Extra Tips: Serve with fresh herbs or a splash of balsamic for added flavor)\n\n## Recipe 3: Garlic Zucchini Noodles\n1. **Prep:** Spiralize zucchini into noodles.\n2. ** Cook:** Heat olive oil in a skillet over medium. Sauté garlic until fragrant, add noodles, cook for 3-4 mins.\n3. **Season & Serve:** Season with salt and pepper. Add cherry tomatoes or nutritional yeast for extra flavor.\n(Extra Tips: Avoid overcooking to keep noodles al dente)\n\nEnjoy!",
  "input: chicken, broccoli, rice, olive oil, garlic, salt, pepper",
  "output: ## Your Ingredients\n1. ChickenBroccoli\n2. Rice\n3. Olive oil\n4. Garlic\n5. Salt\n6. Pepper\n\nHere are my 3 recommended recipes:\n\n## Recipe 1: Chicken and Broccoli Stir-Fry with Rice\n1. **Prep:** Cut chicken into bite-sized pieces, chop broccoli into florets, and cook rice.\n2. **Cook:** Heat olive oil in a skillet over medium-high heat. Add chicken and cook until browned.\n3. **Finish:** Push chicken to the side, add garlic for 30 seconds, then add broccoli and stir-fry until tender, about 5 minutes. Season with salt and pepper. Serve over rice.\n\n(Extra Tips: Add soy sauce, red pepper flakes, or lemon juice for extra flavor.)\n\n## Recipe 2: Garlic Butter Chicken with Broccoli and Rice\n1. **Prep:** Cut chicken, chop broccoli, and cook rice.\n2. **Cook:** Toss chicken with olive oil, garlic, salt, and pepper. Bake at 375°F for 20-25 minutes, or until done.\n3. **Finish:** Steam broccoli until tender. Serve chicken over rice with broccoli and melted butter drizzle.\n\n(Extra Tips: Mix thyme or rosemary into melted butter, or sprinkle Parmesan on top.)\n\n## Recipe 3: One-Pot Chicken and Broccoli with Rice\n1. **Prep:** Cut chicken, chop broccoli, and rinse rice.\n2. **Cook:** Heat olive oil in a pot over medium heat. Add chicken and brown, then add garlic, salt, pepper, rice, and broccoli. Add 2 cups chicken broth or water. Bring to a boil, cover, and simmer for 15-20 minutes, until rice is tender.\n\n(Extra Tips: Use broth for flavor, and add turmeric or smoked paprika. Garnish with parsley or green onions.)\n\nEnjoy!",
  "input: chicken, broccoli, rice, olive oil, garlic, salt\npeppergluten-free, high-protein",
  "output: ## Your Ingredients\n1. Chicken\n2. Broccoli\n3. Rice (ensure gluten-free variety)\n4. Olive oil\n5. Garlic\n6. Salt\n7. Pepper\n\n## Your Dietary Preferences\n1. peppergluten-free\n2. high-protein\n\nHere are my 3 recommended recipes:\n\n## Recipe 1: Chicken & Broccoli Stir-Fry with Rice\n\nThis recipe focuses on maximizing protein with chicken and using a gluten-free rice. \n\n1. **Prep**: Cut chicken into bite-sized pieces. Chop broccoli into florets. Cook rice according to package instructions.\n2. **Cook**: Heat olive oil in a large skillet over medium-high heat. Add chicken and cook until browned on all sides. \n3. **Finish:** Push chicken to the side, add minced garlic, and cook for 30 seconds. Add broccoli florets and stir-fry until tender-crisp, about 5 minutes. Season with salt and pepper. \n4. **Serve:**  Serve the stir-fry over your cooked gluten-free rice.\n\n(Extra Tips: Increase protein further by adding a scoop of protein powder to your rice while cooking)\n\n## Recipe 2: Garlic Butter Chicken with Broccoli & Gluten-Free Rice\n\nThis dish delivers a flavorful and comforting meal with a high-protein emphasis.\n\n1. **Prep:** Cut chicken into bite-sized pieces. Chop broccoli into florets. Cook rice according to package instructions.\n2. **Cook:** Marinate the chicken in a mixture of olive oil, minced garlic, salt, and pepper for at least 30 minutes.  Bake the chicken in a preheated oven at 375°F (190°C) for 20-25 minutes, or until cooked through.\n3. **Finish:**  While the chicken is baking, steam broccoli until tender-crisp.\n4. **Serve:**  Serve the baked chicken over the cooked rice. Top with steamed broccoli and drizzle with melted butter for added richness.\n\n(Extra Tips: Add a sprinkle of lemon zest and fresh parsley to enhance the flavor.)\n\n## Recipe 3: One-Pot Chicken & Broccoli with Gluten-Free Rice\n\nThis simple and nutritious dish is ideal for busy nights. \n\n1. **Prep:** Cut chicken into bite-sized pieces. Chop broccoli into florets. Rinse gluten-free rice thoroughly.\n2. **Cook:** Heat olive oil in a large pot over medium heat. Add chicken and brown on all sides. Add minced garlic, salt, and pepper. Stir in the rice, broccoli florets, and 2 cups of chicken broth.\n3. **Finish:** Bring the mixture to a boil, then reduce heat, cover, and simmer for 15-20 minutes, or until rice is cooked through and the liquid has been absorbed.\n\n(Extra Tips: Add a pinch of turmeric or smoked paprika for a vibrant color and added health benefits)\n\nEnjoy your gluten-free, high-protein meals!",
  "input: pasta, tomatoes, basil, garlic, mozzarella, olive oilvegetarian, high-fiber",
  "output: ## Your Ingredients\n1. Pasta\n2. Tomatoes\n3. Basil\n4. Garlic\n5. Mozzarella\n6. Olive Oil\n\n## Your Dietary Preferences\n1. Vegetarian\n2. High-fiber\n\nHere are my 3 recommended recipes:\n\n## Recipe 1:  Tomato Basil Pasta with High-Fiber Additions\n\nThis classic pasta dish gets a fiber boost with added whole-grain pasta and fiber-rich veggies.\n\n1. **Prep:** Cook whole-grain pasta according to package directions.  Dice tomatoes and finely chop basil.\n2. **Cook:** Heat olive oil in a large skillet over medium heat. Sauté minced garlic until fragrant. Add diced tomatoes and cook until slightly softened, about 5 minutes.\n3. **Finish:**  Stir in cooked pasta, chopped basil, and season with salt and pepper.  Add a handful of chopped spinach or kale for extra fiber and nutrients. Toss to combine.\n4. **Serve:** Top with crumbled mozzarella and a drizzle of olive oil.\n\n(Extra Tips: Add a squeeze of lemon juice for a fresh, zesty flavor that complements the tomatoes and basil)\n\n## Recipe 2:  Mediterranean Pasta Salad with High-Fiber Pasta\n\nThis flavorful salad combines high-fiber pasta with fresh vegetables and a tangy dressing.\n\n1. **Prep:** Cook high-fiber pasta according to package directions. Let cool completely. While pasta cools, chop tomatoes into small pieces, thinly slice red onion, and finely chop basil.\n2. **Assemble:** Combine cooked pasta, chopped tomatoes, red onion, and basil in a large bowl.\n3. **Dressing:** Whisk together olive oil, red wine vinegar, Dijon mustard, salt, and pepper. Pour dressing over pasta mixture and toss to coat.\n4. **Serve:**  Serve immediately or chill in the refrigerator for a few hours.\n\n(Extra Tips: For extra crunch, toss in some chopped cucumber or bell pepper before serving.)\n\n## Recipe 3:  Hearty Lentil and Tomato Pasta with Mozzarella\n\nThis hearty pasta dish is packed with protein and fiber from lentils, while the tomatoes and mozzarella add a touch of Italian flavor.\n\n1. **Prep:** Cook high-fiber pasta according to package directions. While pasta cooks, sauté minced garlic in olive oil until fragrant. Add diced tomatoes and cook for 5 minutes. Stir in cooked lentils and simmer for 5 minutes.\n2. **Finish:**  Combine cooked pasta with lentil and tomato mixture. Season with salt and pepper.\n3. **Serve:** Top with crumbled mozzarella and chopped basil. \n\n(Extra Tips: To enhance the depth of flavor, add a pinch of red pepper flakes for a subtle kick.)\n\nEnjoy your delicious and high-fiber vegetarian meals!",
  "input: togu, ground beef",
  "output: ## Your Ingredients\n1. Tofu\n2. Ground Beef\n\nHere are my 3 recommended recipes:\n\n## Recipe 1:  Tofu and Beef Stir-Fry\n\nThis recipe combines the textures of tofu and ground beef for a hearty and satisfying dish.\n\n1. **Prep:** Crumble tofu and brown ground beef in a skillet over medium heat. Drain off any excess grease.\n2. **Cook:** Add your favorite stir-fry vegetables (such as broccoli, carrots, peppers, onions) to the skillet and cook until tender-crisp.\n3. **Finish:**  Combine soy sauce, honey, and sesame oil in a small bowl. Pour the sauce over the stir-fry ingredients and simmer for 1-2 minutes until thickened.\n4. **Serve:**  Serve over rice or noodles.\n\n(Extra Tips: For added flavor, add a pinch of red pepper flakes or a sprinkle of chopped cilantro)\n\n## Recipe 2: Tofu and Beef Meatballs\n\nThese meatballs are a healthier and more budget-friendly option compared to traditional meat-only meatballs.\n\n1. **Prep:** Combine crumbled tofu, ground beef, breadcrumbs, egg, onion, garlic, salt, and pepper in a bowl. Mix well.\n2. **Cook:** Roll the mixture into small meatballs. Place the meatballs on a baking sheet lined with parchment paper and bake in a preheated oven at 375°F (190°C) for 20-25 minutes, or until cooked through.\n3. **Serve:** Serve the meatballs with your favorite sauce, such as marinara or a spicy tomato sauce.\n\n(Extra Tips: Add grated Parmesan cheese to the meatball mixture for a richer flavor.)\n\n## Recipe 3: Tofu and Beef Tacos\n\nThese tacos offer a protein-packed and flavorful meal with a unique combination of tofu and beef.\n\n1. **Prep:**  Crumble tofu and brown ground beef in a skillet over medium heat. Drain off any excess grease.\n2. **Cook:** Add taco seasoning to the skillet and cook for 1-2 minutes until fragrant.\n3. **Assemble:** Fill tortillas with the tofu and beef mixture, your favorite taco toppings (such as lettuce, tomatoes, onions, cheese), and a dollop of salsa or sour cream.\n\n(Extra Tips: For a spicy kick, add a spoonful of hot sauce or jalapeno peppers.)\n\nEnjoy!",
  "input: carrot, salmon, tomatoes",
  "output: ## Your Ingredients\n1. Carrot\n2. Salmon\n3. Tomatoes\n\nHere are my 3 recommended recipes:\n\n## Recipe 1:  Salmon with Roasted Carrots and Tomatoes\n\nThis dish is simple to prepare and bursting with flavor. \n\n1. **Prep:** Preheat oven to 400°F (200°C). Peel and slice carrots into rounds. Halve cherry tomatoes.\n2. **Cook:** Place salmon fillets on a baking sheet lined with parchment paper. Drizzle with olive oil, and season with salt and pepper. Arrange carrots and tomatoes around the salmon. \n3. **Roast:** Roast for 15-20 minutes, or until salmon is cooked through and carrots are tender.\n\n(Extra Tips:  For added sweetness, toss carrots with a drizzle of maple syrup before roasting. Garnish with fresh dill or parsley.)\n\n## Recipe 2:  Salmon and Tomato Pasta with Carrot Ribbons\n\nThis is a vibrant and healthy pasta dish with a fresh and flavorful twist.\n\n1. **Prep:** Cook pasta according to package instructions.  While pasta cooks, peel carrots and use a vegetable peeler to create long, thin ribbons. Halve cherry tomatoes.\n2. **Cook:**  Heat olive oil in a large skillet over medium heat. Sauté the carrot ribbons until slightly softened, about 5 minutes. Add halved tomatoes and cook for 2 minutes more.\n3. **Finish:**  Add cooked pasta, flaked salmon, and chopped fresh basil to the skillet. Toss to combine. Season with salt and pepper.\n4. **Serve:** Serve immediately with a drizzle of olive oil and a sprinkle of grated Parmesan cheese.\n\n(Extra Tips: For a tangy kick, add a squeeze of lemon juice or a spoonful of pesto.)\n\n## Recipe 3:  Salmon Patties with Carrot and Tomato Relish\n\nThese patties are a great way to use up leftover salmon. \n\n1. **Prep:**  Flake cooked salmon and combine with mashed potato, chopped onion, egg, breadcrumbs, salt, and pepper. Form into patties.\n2. **Cook:**  Heat olive oil in a skillet over medium heat. Cook salmon patties until golden brown and cooked through, about 5-7 minutes per side. \n3. **Relish:**  While patties cook, combine grated carrots, chopped tomatoes, and a splash of red wine vinegar in a small bowl.\n4. **Serve:**  Serve salmon patties with a side of the carrot and tomato relish.\n\n(Extra Tips: For a more flavorful relish, add chopped red onion, fresh dill, or a pinch of sugar.)\n\nEnjoy!",
  "input: salmon, asparagus, olive oil\npaleo, low-carb",
  "output: ## Your Ingredients\n1. Salmon\n2. Asparagus\n3. Olive Oil\n\n## Your Dietary Preferences\n1. Paleo\n2. Low-carb\n\nHere are my 3 recommended recipes:\n\n## Recipe 1:  Pan-Seared Salmon with Roasted Asparagus\n\nThis recipe offers a simple and delicious combination of flavorful salmon and roasted asparagus.\n\n1. **Prep:** Preheat oven to 400°F (200°C). Trim asparagus ends and lightly drizzle with olive oil, salt, and pepper.\n2. **Cook:** Place asparagus on a baking sheet and roast for 10-12 minutes, or until tender-crisp.  While asparagus roasts, heat olive oil in a skillet over medium-high heat. Season salmon fillets with salt and pepper and sear for 3-4 minutes per side, or until cooked through.\n3. **Serve:** Serve seared salmon alongside roasted asparagus.\n\n(Extra Tips:  Add a squeeze of lemon juice to the salmon for a bright and tangy flavor. Garnish with fresh herbs like dill or parsley.)\n\n## Recipe 2:  Salmon and Asparagus Skewers\n\nThis recipe is perfect for grilling or baking and allows for easy portion control. \n\n1. **Prep:** Thread salmon cubes and asparagus spears onto skewers.  Drizzle with olive oil and season with salt, pepper, and your favorite herbs (such as rosemary or thyme). \n2. **Cook:** Grill skewers over medium heat for 5-7 minutes per side, or until salmon is cooked through and asparagus is tender-crisp. Alternatively, bake skewers in a preheated oven at 400°F (200°C) for 15-20 minutes, or until cooked through.\n3. **Serve:**  Serve skewers with a side of your favorite paleo-friendly sauce, such as avocado mayo or chimichurri.\n\n(Extra Tips:  Marinate the salmon and asparagus in a mixture of olive oil, lemon juice, garlic, and herbs for extra flavor before grilling or baking.)\n\n## Recipe 3:  Salmon Salad with Asparagus\n\nThis refreshing salad offers a light and flavorful meal.\n\n1. **Prep:** Flake cooked salmon.  Blanch asparagus spears in boiling water for 2-3 minutes, then shock in ice water.  Slice asparagus spears into bite-sized pieces.\n2. **Salad:** Combine flaked salmon, asparagus pieces, chopped red onion, and your favorite chopped vegetables (such as celery, bell peppers, or cucumber) in a bowl. \n3. **Dressing:** Whisk together olive oil, lemon juice, Dijon mustard, salt, and pepper. Pour dressing over salad and toss to combine.\n\n(Extra Tips:  Add chopped walnuts or pecans for extra crunch and healthy fats.  Serve over a bed of greens for a more substantial meal.)\n\nEnjoy your paleo and low-carb meals!",
  "input: shrimp, zucchini, butter\npescatarian, low-carb",
  "output: ## Your Ingredients\n1. Shrimp\n2. Zucchini\n3. Butter\n\n## Your Dietary Preferences\n1. Pescatarian\n2. Low-carb\n\nHere are my 3 recommended recipes:\n\n## Recipe 1:  Garlic Butter Shrimp with Zucchini Noodles\n\nThis recipe is both flavorful and healthy, perfect for a quick and satisfying meal.\n\n1. **Prep:** Spiralize zucchini into noodles. Peel and mince garlic.\n2. **Cook:** Heat butter in a large skillet over medium heat. Sauté garlic until fragrant. Add shrimp and cook until pink and opaque, about 3-5 minutes. \n3. **Finish:**  Add zucchini noodles to the skillet and cook until slightly softened, about 2-3 minutes. Season with salt and pepper.\n4. **Serve:**  Serve immediately with a squeeze of lemon juice for extra brightness. \n\n(Extra Tips:  Add a pinch of red pepper flakes for a spicy kick.  Garnish with chopped fresh herbs, such as parsley or basil.)\n\n## Recipe 2:  Shrimp and Zucchini Skewers\n\nThis recipe is perfect for grilling or baking, offering a beautiful presentation and a delicious combination of flavors.\n\n1. **Prep:** Thread shrimp and zucchini slices onto skewers.  Drizzle with melted butter and season with salt, pepper, and your favorite herbs (such as thyme or rosemary). \n2. **Cook:** Grill skewers over medium heat for 2-3 minutes per side, or until shrimp is cooked through and zucchini is tender-crisp. Alternatively, bake skewers in a preheated oven at 400°F (200°C) for 10-12 minutes, or until cooked through.\n3. **Serve:** Serve skewers with a side of your favorite low-carb sauce, such as avocado mayo or a lemon-herb vinaigrette.\n\n(Extra Tips:  Marinate shrimp and zucchini in a mixture of melted butter, garlic, lemon juice, and herbs for extra flavor before grilling or baking.)\n\n## Recipe 3:  Shrimp Scampi with Zucchini\n\nThis classic Italian dish gets a low-carb makeover with the addition of zucchini.\n\n1. **Prep:**  Slice zucchini into thin rounds.  Mince garlic.\n2. **Cook:**  Heat butter in a large skillet over medium heat. Add garlic and cook until fragrant. Add shrimp and cook until pink and opaque, about 3-5 minutes. Add white wine and lemon juice to the skillet, and simmer for 1-2 minutes.\n3. **Finish:**  Stir in zucchini slices and cook until tender-crisp, about 2-3 minutes. Season with salt, pepper, and a sprinkle of red pepper flakes for a touch of heat.\n4. **Serve:**  Serve immediately over a bed of greens or alongside your favorite low-carb side dish.\n\n(Extra Tips:  For added flavor, add a tablespoon of chopped fresh parsley or a squeeze of lemon juice to the finished dish.)\n\nEnjoy your pescatarian and low-carb meals!",
  "input: eggs, spinach, mushrooms",
  "output: ## Your Ingredients\n1. Eggs\n2. Spinach\n3. Mushrooms\n\nHere are my 3 recommended recipes:\n\n## Recipe 1:  Mushroom and Spinach Omelette\n\nThis classic breakfast dish is packed with flavor and nutrients. \n\n1. **Prep:** Sauté sliced mushrooms in a skillet with a little olive oil until softened. Set aside.  \n2. **Cook:** Whisk eggs with a splash of milk or water.  Heat a little olive oil in a nonstick skillet. Pour in egg mixture and cook until set, about 2-3 minutes.  \n3. **Finish:**  Top with cooked mushrooms and spinach.  Fold omelette in half. \n4. **Serve:**  Serve hot with a side of your favorite breakfast toast or fruit.\n\n(Extra Tips:  Add a sprinkle of cheese, herbs, or spices to your omelette for extra flavor.)\n\n## Recipe 2:  Spinach and Mushroom Frittata\n\nThis baked dish is perfect for a brunch or light dinner.\n\n1. **Prep:** Preheat oven to 375°F (190°C). Sauté sliced mushrooms in a skillet with olive oil until softened.  Add spinach and cook until wilted.\n2. **Cook:** Whisk eggs with a splash of milk or water, salt, and pepper.  Pour egg mixture over mushroom and spinach mixture in the skillet.  \n3. **Bake:** Bake for 15-20 minutes, or until frittata is set.\n4. **Serve:**  Serve hot or cold.\n\n(Extra Tips:  Add a sprinkle of cheese to the top before baking. Garnish with fresh herbs or a dollop of sour cream before serving.)\n\n## Recipe 3:  Spinach and Mushroom Quiche\n\nThis savory pastry is perfect for a special occasion.\n\n1. **Prep:** Preheat oven to 375°F (190°C).  Blind bake a pie crust.  Sauté sliced mushrooms in a skillet with a little olive oil until softened.  Add spinach and cook until wilted.\n2. **Cook:** Whisk eggs, milk, salt, and pepper.  Pour egg mixture over mushroom and spinach mixture in the baked pie crust.  \n3. **Bake:** Bake for 30-40 minutes, or until quiche is set.  \n4. **Serve:**  Serve hot or cold. \n\n(Extra Tips:  For a richer flavor, add a cup of grated cheese to the egg mixture. Garnish with fresh herbs or a dollop of sour cream before serving.)\n\nEnjoy!",
  "input: apples, cinnamon, oats\ngluten-free, low-sugar",
  "output: ## Your Ingredients\n1. Apples\n2. Cinnamon\n3. Oats (ensure gluten-free variety) \n\n## Your Dietary Preferences\n1. gluten-free\n2. low-sugar\n\nHere are my 3 recommended recipes:\n\n## Recipe 1:  Spiced Apple & Cinnamon Baked Oats\n\nThis recipe is a healthy and satisfying breakfast or snack that's perfect for a gluten-free, low-sugar diet.\n\n1. **Prep:**  Dice apple into small pieces. Combine gluten-free oats, cinnamon, and a pinch of salt in a bowl.\n2. **Cook:**  In a separate bowl, whisk together egg whites, almond milk (or your preferred dairy-free milk), and a little sweetener (such as stevia or erythritol) if desired.  Pour wet ingredients into the dry ingredients and stir to combine.\n3. **Bake:**  Transfer mixture into a greased ramekin or small baking dish. Bake in a preheated oven at 350°F (175°C) for 20-25 minutes, or until set.\n4. **Serve:**  Serve warm with a sprinkle of cinnamon or a drizzle of maple syrup (use sparingly for low-sugar).\n\n(Extra Tips:  Add chopped nuts, seeds, or a dollop of unsweetened applesauce for extra flavor and texture. Top with a sprinkle of cinnamon and a sliced apple for a festive look.)\n\n## Recipe 2:  Apple Cinnamon Oatmeal with Gluten-Free Oats\n\nThis classic oatmeal recipe is adapted to be gluten-free and low-sugar.\n\n1. **Prep:**  Dice apples into small pieces. \n2. **Cook:** Combine gluten-free oats, water, and a pinch of salt in a saucepan. Bring to a boil, then reduce heat to low and simmer for 5-7 minutes, stirring occasionally, until oats are cooked through. Stir in diced apples and cinnamon. \n3. **Serve:**  Serve warm with a sprinkle of cinnamon or a drizzle of maple syrup (use sparingly for low-sugar).\n\n(Extra Tips:  For extra sweetness, add a teaspoon of stevia or erythritol while cooking.  Top with sliced almonds, berries, or a dollop of unsweetened almond butter.)\n\n## Recipe 3:  Apple Cinnamon Smoothie with Gluten-Free Oats\n\nThis smoothie is a quick and easy way to enjoy a healthy breakfast or snack. \n\n1. **Prep:**  Dice apple into small pieces. Blend gluten-free oats with almond milk (or your preferred dairy-free milk) until smooth. \n2. **Assemble:**  Combine blended oat mixture with diced apple, cinnamon, a pinch of salt, and a little sweetener (such as stevia or erythritol) if desired. Blend until smooth. \n3. **Serve:**  Serve immediately.\n\n(Extra Tips:  Add a scoop of protein powder or chia seeds for added nutrition.  Top with a sprinkle of cinnamon or a dollop of unsweetened almond butter.)\n\nEnjoy your gluten-free, low-sugar meals!",
]

# Define a function to send input to the model and retrieve the response
# ingredients are a text separated by commas
# dietary preferences are a text separated by commas (optional)
def generate_recipe(ingredients: str, dietary_preferences="NOTHING"):
    # if dietary preferences not specified
    if dietary_preferences == "NOTHING":
        prompt = f"input: {ingredients}"
    else:
        prompt = f"input: {ingredients}\n{dietary_preferences}"
    predefined_outputs.append(prompt)
    result = model.generate_content(predefined_outputs)
    return result

# Example to generate recipe
ingredients = "steak, tomatoes, orange"
restrictions = "high-protein"
output = generate_recipe(ingredients, restrictions) #take out restrictions from the arguments if you do not want to specify any
print("Model response:\n", output.text)